/**
 * -----------------------------------------------------------------------------
 * API Type Utilities
 * -----------------------------------------------------------------------------
 *
 * This file provides strongly-typed utilities derived from the OpenAPI
 * `paths` schema generated by `openapi-typescript` using the command :
 * "npm run swagger" and stored in '~/lib/swagger.ts'.
 *
 * Its purpose is to:
 *
 *  • Enforce compile-time validation of API paths and HTTP methods
 *  • Infer request parameters and JSON bodies from the OpenAPI contract
 *  • Infer successful response payload types (200–204)
 *  • Provide higher-level helpers (e.g. paginated response detection)
 *
 * These types power:
 *  - apiFetch()
 *  - useFetchQuery()
 *  - useFetchMutation()
 *
 * The goal is zero manual typing in the application layer while remaining
 * strictly aligned with the backend contract.
 * -----------------------------------------------------------------------------
 */

import { paths } from "~/lib/swagger";

/**
 * All valid API route strings (e.g. "/api/login").
 */
export type ApiPath = keyof paths;

/**
 * Supported HTTP methods as defined by OpenAPI.
 */
type HttpMethod =
  | "get"
  | "post"
  | "put"
  | "patch"
  | "delete"
  | "options"
  | "trace"
  | "head";

/**
 * Extract valid HTTP methods for a given path.
 *
 * Example:
 *   ApiPathMethod<"/api/login"> → "post"
 */
export type ApiPathMethod<P extends ApiPath> = Extract<
  keyof paths[P],
  HttpMethod
>;

/**
 * Helper: resolves to T if T is not `never`, otherwise `Fallback`
 */
type IfNotNever<T, Fallback> = [T] extends [never] ? Fallback : T;

/**
 * Extract request parameters (path/query) for a given endpoint.
 *
 * Fully preserves OpenAPI schema typing:
 *  - Required path params
 *  - Enum query params
 *  - Nested query structures
 */
export type ApiRequestParams<
  P extends ApiPath,
  M extends ApiPathMethod<P>,
> = paths[P][M] extends { parameters: infer Params }
  ? Params & {
      path?: IfNotNever<
        Params extends { path?: infer Path } ? NonNullable<Path> : never,
        Record<string, string | number>
      >;
      query?: IfNotNever<
        Params extends { query?: infer Query } ? NonNullable<Query> : never,
        Record<string, string | number | boolean | string[] | null | undefined>
      >;
      header?: never;
      cookie?: never;
    }
  : {
      path?: Record<string, string | number>;
      query?: Record<
        string,
        string | number | boolean | string[] | null | undefined
      >;
    };

/**
 * Extract JSON request body type for a given endpoint.
 *
 * If no JSON body is defined, resolves to `never`.
 */
export type ApiRequestBody<
  P extends ApiPath,
  M extends ApiPathMethod<P>,
> = paths[P][M] extends {
  requestBody?: {
    content: {
      "application/json": infer R;
    };
  };
}
  ? R
  : never;

/**
 * Successful HTTP status codes considered valid responses.
 */
type SuccessStatus = 200 | 201 | 202 | 203 | 204;

/**
 * Extract JSON response type from successful status codes.
 *
 * Supports:
 *  - 200 OK
 *  - 201 Created
 *  - 202 Accepted
 *  - 203 Non-Authoritative Information
 *  - 204 No Content (→ resolves to `never` or `void` depending on schema)
 *
 * Prevents hardcoding to 200 only.
 */
export type ApiResponse<
  P extends ApiPath,
  M extends ApiPathMethod<P>,
> = paths[P][M]["responses"] extends infer R
  ? {
      [K in keyof R & SuccessStatus]: R[K] extends {
        content: { "application/ld+json": infer LDJSON }; // prefer ld+json
      }
        ? LDJSON
        : R[K] extends { content: { "application/json": infer JSON } } // fallback to json
          ? JSON
          : never;
    }[keyof R & SuccessStatus]
  : never;

/**
 * Detect paginated LD+JSON responses following API Platform's structure:
 *
 * {
 *   member: T[]
 *   totalItems: number
 *   view: { first, last, next, previous }
 * }
 */
export type PaginatedApiResponse<
  P extends ApiPath,
  M extends ApiPathMethod<P>,
> =
  ApiResponse<P, M> extends {
    member: infer D;
    totalItems: unknown;
  }
    ? D extends unknown[]
      ? ApiResponse<P, M>
      : never
    : never;
