/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/actions/{stock_category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all actions, specific to a stock category */
        get: operations["331b62c6cfe39ae53eb55c4b5f423c9c"];
        put?: never;
        /** Insert new actions in the specified stock category */
        post: operations["460f76563da78d49cac27d90f6280ff4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actions/{stock_category}/{action_ID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an action by id in the specified stock category */
        get: operations["0860d0739a5643134ee5b943ccf40bd3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate user and return JWT */
        post: operations["fe6544959270bd59edaecbc87ce09a4c"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/errors/{stock_category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct errors in actions, so in stocks too */
        patch: operations["ad26345d7319f72aa2ba8872e27fc3c7"];
        trace?: never;
    };
    "/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add corrupted data to known_errors table */
        post: operations["67cf18badd8d1e56bcc93ea516184d4f"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/errors/{stock_category}/correctExpDate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Correct wrong expiration_date */
        patch: operations["f3767d2b95e3d9782fd7d64dae6a3cb7"];
        trace?: never;
    };
    "/productCategory/{stock_global_category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get actual stock data */
        get: operations["ec2ea90dc22cd101d430e4e75bd71abc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qr-code/{qr_code_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the requested qr code data matching the qr_code_id */
        get: operations["5168e82022c69e25a348f7ecc7e247ab"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Delete qr code */
        patch: operations["743db6fca556baab5f4ec0e12d1a1ad6"];
        trace?: never;
    };
    "/qr-code/{stock_category}/{product_code}/{lot_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch how much of a product has been already placed on pallets */
        get: operations["5d2f667d45dbd8aa74304236f1ca00c8"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qr-code/{stock_category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new QR code entry */
        post: operations["243f9d365ae979ae09c642f27dda1a4f"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/qr-code/{stock_category}/{qr_code_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modify an existing QR code entry */
        patch: operations["a23be3f6247b5d045575fe593e651e07"];
        trace?: never;
    };
    "/stocks/{stock_category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get actual stock data */
        get: operations["3affd2f60f651f8329274f7b8d06c203"];
        put?: never;
        /** Save a stock in database, which is the stock at a precize date. */
        post: operations["1988dd14be8f06b9096f02e3b5ad82a6"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stocks_join_product_category/{stock_category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get actual stock data, joined to product's informations */
        get: operations["270886d50fc8c945e01a672f4a1eadd3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all users */
        get: operations["21374aa54f8c94a3dfd9abf9efe9ac86"];
        put?: never;
        /** Create a new user */
        post: operations["c23061913c7f3c33a5e8f57461149771"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_ID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an user by ID */
        get: operations["cd7cf90bd70793032e47d1fee7bc665a"];
        put?: never;
        post?: never;
        /** Delete a user */
        delete: operations["97fd6c75f1cdb47d086d2fa8a7063640"];
        options?: never;
        head?: never;
        /** Modify a user */
        patch: operations["d34c02a1e3276e417eb75f2b6e91cf26"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** @example 1 */
            id: number;
            /** @example John */
            first_name: string;
            /** @example Doe */
            last_name: string;
            /** @example johndoe */
            username: string;
            /**
             * Format: email
             * @example john@example.com
             */
            email: string;
            /** @enum {unknown} */
            role: "admin" | "user";
            user_preferences?: {
                /**
                 * @example dark
                 * @enum {unknown|null}
                 */
                theme?: "light" | "dark" | "system" | null;
                /** @example #ff0000 */
                tint_color?: string | null;
                /** @enum {unknown|null} */
                language?: "EN" | "EU" | "FR" | null;
            };
        };
        Action: {
            id: number;
            quantity: number;
            comment: string;
            product_code: string;
            lot_number: string;
            created_by_id: number;
            /** Format: date-time */
            created_at: string;
            action_id: number;
            transaction: string;
        };
        Stock: {
            /** @example 1 */
            id: number;
            /** @example 144 */
            product_code: string;
            /** @example DSC050525 */
            lot_number: string;
            /** @example 100 */
            quantity: number;
            /**
             * Format: date
             * @example 2025-05-05
             */
            expiration_date: string;
        };
        Stock_join_product_category: {
            /** @example 1 */
            id: number;
            /** @example 144 */
            product_code: string;
            /** @example DSC050525 */
            lot_number: string;
            /** @example 100 */
            quantity: number;
            /**
             * Format: date
             * @example 2025-05-05
             */
            expiration_date: string;
            /** @example Gésiers de dinde */
            product_name: string;
            /** @example GDE | F | Boite */
            product_specificity?: string;
        };
        /** @example [
         *       "id",
         *       "product_code",
         *       "lot_number",
         *       "quantity",
         *       "expiration_date"
         *     ] */
        stock_selected_elts: string[];
        /** @example [
         *       "product_code",
         *       "product_name",
         *       "product_specificity"
         *     ] */
        product_category_selected_elts: string[];
        /** @example [
         *       "id",
         *       "product_code",
         *       "lot_number",
         *       "quantity",
         *       "expiration_date"
         *     ] */
        stock_selected_elts_join_product_category_table: string[];
        filter_params: {
            /**
             * @description Code produit
             * @example 309
             */
            product_code?: string;
            /**
             * @description Numéro de lot
             * @example GDE050528
             */
            lot_number?: string;
            /**
             * @description Quantité
             * @example 43
             */
            quantity?: number;
            /**
             * Format: date
             * @description Date d'expiration
             * @example 2028-05-05
             */
            expiration_date?: string;
        };
        filter_params_PC: {
            /**
             * @description Code produit
             * @example 309
             */
            product_code: string;
            /**
             * @description Numéro de lot
             * @example GDE050528
             */
            product_name: string;
            /**
             * @description Spécificité du produit. En fonction de la catégorie de stock concernée, peut être un code de lot (GDE), une sous catégorie des stocks matières premières (F, C...) ou bien un type d'emballage (boite ou couvercle)
             * @example 43
             */
            product_specificity: string;
        };
        filter_params_join_product_category: {
            /**
             * @description Code produit
             * @example 309
             */
            product_code?: string;
            /**
             * @description Numéro de lot
             * @example GDE050528
             */
            lot_number?: string;
            /**
             * @description Quantité
             * @example 43
             */
            quantity?: number;
            /**
             * Format: date
             * @description Date d'expiration
             * @example 2028-05-05
             */
            expiration_date?: string;
            /**
             * @description Product real name
             * @example Gésiers de dinde
             */
            product_name?: string;
            /**
             * @description Differs depending on stock category : can be a product lot code, a stock category, or a type of content
             * @example GDE | F | Boite
             */
            product_specificity?: string;
        };
        /** @example {
         *       "errors_in_stocks": {
         *         "309": {
         *           "GDE040428": {
         *             "react_ids": [
         *               1,
         *               8
         *             ],
         *             "error_message": "Incorrect quantity value : -45"
         *           }
         *         },
         *         "993": {
         *           "ADR020228": {
         *             "react_ids": [
         *               3,
         *               45,
         *               5
         *             ],
         *             "error_message": "Incorrect quantity value : -49"
         *           },
         *           "ADR050529": {
         *             "react_ids": [
         *               4
         *             ],
         *             "error_message": "Incorrect quantity value : -2"
         *           }
         *         }
         *       },
         *       "blocking_errors": {
         *         "127": {
         *           "FDC020222": {
         *             "react_ids": [
         *               35,
         *               36,
         *               38
         *             ],
         *             "error_message": "Errors..."
         *           }
         *         },
         *         "001": {
         *           "CDA030230": {
         *             "react_ids": [
         *               11,
         *               14
         *             ],
         *             "error_message": "Unable to find an expiration date for actual product"
         *           }
         *         }
         *       }
         *     } */
        ErrorResponse: {
            /** @description Code produit */
            errors_in_stocks?: {
                [key: string]: components["schemas"]["LotNumberAssociateErrors"];
            };
            /** @description Code produits */
            blocking_errors?: {
                [key: string]: components["schemas"]["LotNumberAssociateErrors"];
            };
        };
        /** @description Numéro de lot */
        LotNumberAssociateErrors: {
            [key: string]: components["schemas"]["ErrorDetail"];
        };
        ErrorDetail: {
            /** @example [
             *       5,
             *       6
             *     ] */
            react_ids?: number[];
            /** @example Incorrect quantity value : -85 */
            error_message?: string;
        };
        newActions: (components["schemas"]["Action"] | components["schemas"]["Action"] | components["schemas"]["Action"])[];
        Wrong_actions: {
            error_in_stock?: components["schemas"]["Action"][];
            error_in_insert?: components["schemas"]["Action"][];
        };
        AimDate: {
            /**
             * Format: date-time
             * @example 2025-04-04 14:54:12
             */
            aimdate: string;
        };
        Stock_content: (components["schemas"]["Stock"] | components["schemas"]["Stock"])[];
        Error_manager_informations_to_modify_array: {
            /** @example 309 */
            product_code?: string;
            /** @example GDE050528 */
            lot_number?: string;
            /** @example 45 */
            quantity?: number;
            /** @example 2 */
            action_id?: number;
            /** @example 34009 */
            transaction?: string;
        };
        Error_manager_corrupted_data: {
            /** @example 309 */
            product_code?: string;
            /** @example GDE050528 */
            lot_number?: string;
        };
        Error_manager_add_corrupted_data: (components["schemas"]["Error_manager_corrupted_data"] | components["schemas"]["Error_manager_corrupted_data"])[];
        Error_manager_expiration_date: {
            /** @example 309 */
            product_code?: string;
            /** @example GDE050528 */
            lot_number?: string;
            /**
             * Format: date
             * @example 2028-05-05
             */
            expiration_date?: string;
        };
        Error_manager_correct_expiration_date: (components["schemas"]["Error_manager_expiration_date"] | components["schemas"]["Error_manager_expiration_date"])[];
        /**
         * @description Objet associatif dont les clés sont des identifiants uniques de lignes SQL (ex : 3, 6, 42). Les valeurs respectent le schéma Error_manager_informations_to_modify_array.
         * @example {
         *       "4": {
         *         "product_code": "207IGP",
         *         "lot_number": "CC130529",
         *         "quantity": 39,
         *         "action_id": 1,
         *         "transaction": "25009"
         *       },
         *       "9": {
         *         "product_code": "309",
         *         "lot_number": "GDE130529",
         *         "quantity": 43,
         *         "action_id": 2,
         *         "transaction": "43898"
         *       }
         *     }
         */
        Error_manager_informations_to_modify: {
            [key: string]: components["schemas"]["Error_manager_informations_to_modify_array"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "331b62c6cfe39ae53eb55c4b5f423c9c": {
        parameters: {
            query?: {
                /** @description Maximum number of results to return */
                limit?: number;
                /** @description Number of items to skip (for pagination) */
                offset?: number;
                /** @description Order by column */
                order_by?: "created_at" | "created_by_id" | "id" | "comment" | "lot_number" | "product_code" | "action_id" | "quantity" | "transaction";
                /** @description Sort order: asc or desc */
                sort?: "asc" | "desc";
            };
            header?: never;
            path: {
                stock_category: "PF_G" | "PF_M" | "MP_F" | "MP_S" | "MP_C" | "EMB";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Actions fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Actions fetched successfully */
                        message?: string;
                        data?: components["schemas"]["Action"][];
                    };
                    "application/xml": {
                        /** @example Actions fetched successfully */
                        message?: string;
                        data?: components["schemas"]["Action"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                };
            };
        };
    };
    "460f76563da78d49cac27d90f6280ff4": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_category: "PF_G" | "PF_M" | "MP_F" | "MP_S" | "MP_C" | "EMB";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Action"][];
                "application/xml": components["schemas"]["Action"][];
            };
        };
        responses: {
            /** @description New actions have been inserted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example New actions have been inserted successfully */
                        message?: string;
                    };
                    "application/xml": {
                        /** @example New actions have been inserted successfully */
                        message?: string;
                    };
                };
            };
            /** @description Some actions have led to errors in stocks */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"][];
                    "application/xml": components["schemas"]["ErrorResponse"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                };
            };
        };
    };
    "0860d0739a5643134ee5b943ccf40bd3": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_category: "PF_G" | "PF_M" | "MP_F" | "MP_S" | "MP_C" | "EMB";
                actionID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Action fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Action fetched successfully */
                        message?: string;
                        data?: components["schemas"]["Action"];
                    };
                    "application/xml": {
                        /** @example Action fetched successfully */
                        message?: string;
                        data?: components["schemas"]["Action"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                };
            };
        };
    };
    fe6544959270bd59edaecbc87ce09a4c: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example yourPassword
                     */
                    password: string;
                };
                "application/xml": {
                    /**
                     * Format: email
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * Format: password
                     * @example yourPassword
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Successful login */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Successful login */
                        message?: string;
                        data?: {
                            jwt?: string;
                            expireAt?: number;
                            user_info?: {
                                id?: number;
                                email?: string;
                                /** @enum {unknown} */
                                role?: "admin" | "user";
                                username?: string;
                                first_name?: string;
                                last_name?: string;
                            };
                            user_preferences?: {
                                /** @enum {unknown|null} */
                                theme?: "light" | "dark" | "system" | null;
                                tint_color?: string | null;
                                /** @enum {unknown|null} */
                                language?: "EN" | "EU" | "FR" | null;
                            };
                        };
                    };
                    "application/xml": {
                        /** @example Successful login */
                        message?: string;
                        data?: {
                            jwt?: string;
                            expireAt?: number;
                            user_info?: {
                                id?: number;
                                email?: string;
                                role?: string;
                                username?: string;
                                first_name?: string;
                                last_name?: string;
                            };
                            user_preferences?: {
                                theme?: string | null;
                                tint_color?: string | null;
                                language?: string | null;
                            };
                        };
                    };
                };
            };
            /** @description Missing email or password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Login failed. Incorrect password or user not registered. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ad26345d7319f72aa2ba8872e27fc3c7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_category: "PF_G" | "PF_M" | "MP_F" | "MP_S" | "MP_C" | "EMB";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Error_manager_informations_to_modify"];
            };
        };
        responses: {
            /** @description Stocks updated without detected new errors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Stocks updated without detected new errors */
                        message?: string;
                    };
                };
            };
            /** @description Stocks updated with potential new errors */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wrong_actions"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                };
            };
        };
    };
    "67cf18badd8d1e56bcc93ea516184d4f": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Error_manager_add_corrupted_data"];
            };
        };
        responses: {
            /** @description New corrupted products have been referenced successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example New corrupted products have been referenced successfully */
                        message?: string;
                    };
                    "application/xml": {
                        /** @example New corrupted products have been referenced successfully */
                        message?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                };
            };
        };
    };
    f3767d2b95e3d9782fd7d64dae6a3cb7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_category: "PF_G" | "PF_M" | "MP_F" | "MP_S" | "MP_C" | "EMB";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    to_correct_products: components["schemas"]["Error_manager_correct_expiration_date"];
                };
            };
        };
        responses: {
            /** @description Expiration date updated successfuly */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Expiration date updated successfuly */
                        message?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                };
            };
        };
    };
    ec2ea90dc22cd101d430e4e75bd71abc: {
        parameters: {
            query?: {
                /** @description Maximum number of results to return */
                limit?: number;
                /** @description Number of items to skip (for pagination) */
                offset?: number;
                /** @description Order by column */
                order_by?: "product_code" | "product_name" | "product_specificity";
                /** @description Sort order: asc or desc */
                sort?: "asc" | "desc";
                /** @description Filter value that appeared multiple times */
                distinct?: boolean;
                /** @description Select which data we want to fetch */
                required_elts?: components["schemas"]["product_category_selected_elts"];
                /** @description Add conditions in where clause to filter data */
                filter_params?: components["schemas"]["filter_params_PC"];
            };
            header?: never;
            path: {
                stock_global_category: "PF" | "MP" | "EMB";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product Category data retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Stock data retrieved successfully */
                        message?: string;
                        data?: components["schemas"]["filter_params_PC"][];
                    };
                    "application/xml": {
                        /** @example Product Category data retrieved successfully */
                        message?: string;
                        data?: components["schemas"]["filter_params_PC"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stock not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "5168e82022c69e25a348f7ecc7e247ab": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qr_code_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Qr code fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Actions fetched successfully */
                        message?: string;
                        data?: {
                            id?: number;
                            product_code?: string;
                            lot_number?: string;
                            quantity?: number;
                            /** Format: date */
                            expiration_date?: string;
                        };
                    };
                    "application/xml": {
                        /** @example Actions fetched successfully */
                        message?: string;
                        data?: components["schemas"]["Action"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                };
            };
        };
    };
    "743db6fca556baab5f4ec0e12d1a1ad6": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the QR code to delete */
                qr_code_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description QR code deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example QR code deleted successfully */
                        message?: string;
                    };
                    "application/xml": {
                        message?: string;
                    };
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Invalid request data */
                        error?: string;
                    };
                    "application/xml": {
                        error?: string;
                    };
                };
            };
        };
    };
    "5d2f667d45dbd8aa74304236f1ca00c8": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_code: string;
                lot_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Quantity fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Actions fetched successfully */
                        message?: string;
                        data?: {
                            quantity?: number;
                        };
                    };
                    "application/xml": {
                        /** @example Actions fetched successfully */
                        message?: string;
                        data?: components["schemas"]["Action"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                };
            };
            /** @description QR code not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example QR code not found */
                        error?: string;
                    };
                    "application/xml": {
                        error?: string;
                    };
                };
            };
        };
    };
    "243f9d365ae979ae09c642f27dda1a4f": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_category: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example PRD12345 */
                    product_code?: string;
                    /** @example LOT98765 */
                    lot_number?: string;
                    /** @example 100 */
                    quantity?: number;
                    /**
                     * Format: date-time
                     * @example 2025-12-31T00:00:00Z
                     */
                    expiration_date?: string;
                };
                "application/xml": {
                    product_code?: string;
                    lot_number?: string;
                    quantity?: number;
                    /** Format: date-time */
                    expiration_date?: string;
                };
            };
        };
        responses: {
            /** @description QR code created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example QR code created successfully */
                        message?: string;
                        data?: {
                            id?: number;
                        };
                    };
                    "application/xml": {
                        message?: string;
                        data?: {
                            id?: number;
                        };
                    };
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Invalid request data */
                        error?: string;
                    };
                    "application/xml": {
                        error?: string;
                    };
                };
            };
        };
    };
    a23be3f6247b5d045575fe593e651e07: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the QR code to modify */
                qr_code_id: number;
                stock_category: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example 993 */
                    product_code?: string;
                    /** @example GDE050525 */
                    lot_number?: string;
                    /** @example 150 */
                    quantity?: number;
                    /** Format: date */
                    expiration_date?: string;
                };
                "application/xml": {
                    /** @example 993 */
                    product_code?: string;
                    /** @example GDE050525 */
                    lot_number?: string;
                    /** @example 150 */
                    quantity?: number;
                    /** Format: date */
                    expiration_date?: string;
                };
            };
        };
        responses: {
            /** @description QR code updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example QR code updated successfully */
                        message?: string;
                    };
                    "application/xml": {
                        message?: string;
                    };
                };
            };
            /** @description Invalid request data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Invalid request data */
                        error?: string;
                    };
                    "application/xml": {
                        error?: string;
                    };
                };
            };
            /** @description QR code not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example QR code not found */
                        error?: string;
                    };
                    "application/xml": {
                        error?: string;
                    };
                };
            };
        };
    };
    "3affd2f60f651f8329274f7b8d06c203": {
        parameters: {
            query?: {
                /** @description Maximum number of results to return */
                limit?: number;
                /** @description Number of items to skip (for pagination) */
                offset?: number;
                /** @description Order by column */
                order_by?: "id" | "product_code" | "lot_number" | "quantity" | "expiration_date";
                /** @description Sort order: asc or desc */
                sort?: "asc" | "desc";
                /** @description Filter value that appeared multiple times */
                distinct?: boolean;
                /** @description Select which data we want to fetch */
                required_elts?: components["schemas"]["stock_selected_elts"];
                /** @description Add conditions in where clause to filter data */
                filter_params?: components["schemas"]["filter_params"];
            };
            header?: never;
            path: {
                stock_category: "PF_G" | "PF_M" | "MP_F" | "MP_S" | "MP_C" | "EMB";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stock data retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Stock data retrieved successfully */
                        message?: string;
                        data?: components["schemas"]["Stock"][];
                    };
                    "application/xml": {
                        /** @example Stock data retrieved successfully */
                        message?: string;
                        data?: components["schemas"]["Stock"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stock not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "1988dd14be8f06b9096f02e3b5ad82a6": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                stock_category: "PF_G" | "PF_M" | "MP_F" | "MP_S" | "MP_C" | "EMB";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New actions have been inserted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example New stock has been successfully saved in database */
                        message?: string;
                    };
                    "application/xml": {
                        /** @example New stock has been successfully saved in database */
                        message?: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Unauthorized */
                        error?: string;
                    };
                };
            };
        };
    };
    "270886d50fc8c945e01a672f4a1eadd3": {
        parameters: {
            query?: {
                /** @description Maximum number of results to return */
                limit?: number;
                /** @description Number of items to skip (for pagination) */
                offset?: number;
                /** @description Order by column */
                order_by?: "id" | "product_code" | "lot_number" | "quantity" | "expiration_date";
                /** @description Sort order: asc or desc */
                sort?: "asc" | "desc";
                /** @description Filter value that appeared multiple times */
                distinct?: boolean;
                /** @description Select which data we want to fetch */
                required_elts?: components["schemas"]["stock_selected_elts_join_product_category_table"];
                /** @description Add conditions in where clause to filter data */
                filter_params?: components["schemas"]["filter_params_join_product_category"];
            };
            header?: never;
            path: {
                stock_category: "PF_G" | "PF_M" | "MP_F" | "MP_S" | "MP_C" | "EMB";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stock and product_category data retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Stock and product_category data retrieved successfully */
                        message?: string;
                        data?: components["schemas"]["Stock_join_product_category"][];
                    };
                    "application/xml": {
                        /** @example Stock and product_category data retrieved successfully */
                        message?: string;
                        data?: components["schemas"]["Stock_join_product_category"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Stock not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "21374aa54f8c94a3dfd9abf9efe9ac86": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Users fetched successfully */
                        message?: string;
                        data?: components["schemas"]["User"][];
                    };
                    "application/xml": {
                        /** @example Users fetched successfully */
                        message?: string;
                        data?: components["schemas"]["User"][];
                    };
                };
            };
            /** @description Unauthorized, login required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Login required */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Login required */
                        error?: string;
                    };
                };
            };
        };
    };
    c23061913c7f3c33a5e8f57461149771: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    first_name?: string;
                    last_name?: string;
                    username: string;
                    email: string;
                    password: string;
                    role?: string;
                    user_preferences?: {
                        theme?: string | null;
                        tint_color?: string | null;
                        language?: string | null;
                    };
                };
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example User created successfully */
                        message?: string;
                    };
                    "application/xml": {
                        /** @example User created successfully */
                        message?: string;
                    };
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized, login required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Login required */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Login required */
                        error?: string;
                    };
                };
            };
            /** @description Failed to create user */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cd7cf90bd70793032e47d1fee7bc665a: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_ID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User fetched successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example User fetched successfully */
                        message?: string;
                        data?: components["schemas"]["User"];
                    };
                    "application/xml": {
                        /** @example User fetched successfully */
                        message?: string;
                        data?: components["schemas"]["User"];
                    };
                };
            };
            /** @description Unauthorized, login required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Login required */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Login required */
                        error?: string;
                    };
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "97fd6c75f1cdb47d086d2fa8a7063640": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_ID: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example User deleted successfully */
                        message?: string;
                    };
                    "application/xml": {
                        /** @example User deleted successfully */
                        message?: string;
                    };
                };
            };
            /** @description Unauthorized, login required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Login required */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Login required */
                        error?: string;
                    };
                };
            };
            /** @description Unauthorized */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Unauthorized: You can only delete your own profile */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Unauthorized: You can only delete your own profile */
                        error?: string;
                    };
                };
            };
            /** @description Failed to delete user */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    d34c02a1e3276e417eb75f2b6e91cf26: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_ID: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    user_preferences?: {
                        theme?: string | null;
                        tint_color?: string | null;
                        language?: string | null;
                    };
                    user_info?: {
                        first_name?: string;
                        last_name?: string;
                        username?: string;
                        email?: string;
                        role?: string;
                    };
                };
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example User updated successfully */
                        message?: string;
                    };
                    "application/xml": {
                        /** @example User updated successfully */
                        message?: string;
                    };
                };
            };
            /** @description Invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized, login required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Login required */
                        error?: string;
                    };
                    "application/xml": {
                        /** @example Login required */
                        error?: string;
                    };
                };
            };
            /** @description No sufficient permissions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed to update user */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
